config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations"}
  root to: 'pages#home'

  namespace :admin do
    resources :users, only: [:index, :update]
  end

  resources :uses, only: [:new, :create, :edit, :update, :destroy]
  resources :appliances, only: [:index, :show, :new, :create, :edit, :update, :destroy], shallow: true do
    resources :sources, only: [:new, :create, :edit, :update, :destroy]
    member do
      post 'duplicate'
    end
  end

  resources :projects, only: [:index, :show, :new, :create, :edit, :update, :destroy], shallow: true do
    resources :project_appliances, only: [:new, :create, :edit, :update, :destroy]
    resources :solar_systems, only: [:new, :create, :edit, :update, :destroy]
    member do
      get 'appliances'
      post 'duplicate'
    end
  end

  get 'projects/public/:token', to: 'projects#public', as: 'public_project'
  post 'projects/public/:token/load', to: 'projects#load', as: 'project_load'

  get 'appliance_refresh_load', to: 'appliances#refresh_load'
  get 'project_appliance_refresh_load', to: 'project_appliances#refresh_load'

  get 'power_components', to: 'pages#power_components'
  resources :power_systems, only: [:new, :create, :edit, :update, :destroy]
  resources :batteries, only: [:new, :create, :edit, :update, :destroy]
  resources :solar_panels, only: [:new, :create, :edit, :update, :destroy]
  resources :communication_modules, only: [:new, :create, :edit, :update]
  resources :distributions, only: [:new, :create, :edit, :update]

  post 'request_registration', to: 'pages#request_registration'
end

app/models/appliance.rb
class Appliance < ApplicationRecord
  belongs_to :user
  belongs_to :use
  has_many :sources, dependent: :destroy
  has_many :project_appliances, dependent: :destroy
  has_many :projects, -> { distinct }, through: :project_appliances

  scope :ordered, -> { order(updated_at: :desc) }

  include PgSearch::Model
  pg_search_scope :search,
    against: [ :name ],
    associated_against: {
      use: [ :name ]
    },
    using: {
      tsearch: {
        prefix: true,
        dictionary: "english",
        any_word: true
      }
    },
    order_within_rank: "updated_at DESC"

  mount_uploader :photo, PhotoUploader

  before_save :set_power_factor_and_starting_coeff

  DAY_TIME = 6
  NIGHT_TIME = 18
  TYPES = ["AC", "DC"]
  RATES = {
    "1" => "10",
    "0.9" => "9",
    "0.8" => "8",
    "0.7" => "7",
    "0.6" => "6",
    "0.5" => "5",
    "0.4" => "4",
    "0.3" => "3",
    "0.2" => "2",
    "0.1" => "1"
  }
  GRADES = ["A+++", "A++", "A+", "A", "B", "C", "D", "E", "F", "G"]
  GRADE_CLASSES = {
    "A+++" => "grade-a-plus-plus-plus",
    "A++" => "grade-a-plus-plus",
    "A+" => "grade-a-plus",
    "A" => "grade-a",
    "B" => "grade-b",
    "C" => "grade-c",
    "D" => "grade-d",
    "E" => "grade-e",
    "F" => "grade-f",
    "G" => "grade-g"
  }

  validates :name, presence: true
  validates :power, numericality: {greater_than_or_equal_to: 0, allow_nil: true}
  validates :power_factor, numericality: {greater_than: 0, less_than_or_equal_to: 1, allow_nil: true}
  validates :starting_coefficient, numericality: {greater_than_or_equal_to: 1, allow_nil: true}
  validates :current_type, inclusion: {in: TYPES, allow_blank: true}, presence: true
  validates :voltage_min, numericality: {greater_than: 0, allow_nil: true}
  validates :voltage_max, numericality: {greater_than: 0, allow_nil: true}
  validates :energy_grade, inclusion: {in: GRADES, allow_blank: true}

  monetize :price_min_cents, allow_nil: true, with_currency: :eur
  monetize :price_max_cents, allow_nil: true, with_currency: :eur

  def apparent_power
    if power and power_factor
      (power / power_factor)
    end
  end

  def peak_power
    if apparent_power and starting_coefficient
      apparent_power * starting_coefficient
    end
  end

  def daily_consumption
    if apparent_power
      (0..23).reduce(0) { |sum, hour| sum + method("hourly_rate_#{hour}").call.to_f / 10 } * apparent_power
    end
  end

  def daytime_consumption
    if apparent_power
      (DAY_TIME...NIGHT_TIME).reduce(0) { |sum, hour| sum + method("hourly_rate_#{hour}").call.to_f / 10 } * apparent_power
    end
  end

  def nighttime_consumption
    daily_consumption - daytime_consumption if apparent_power
  end

  (0..23).each do |hour|
    define_method("hourly_consumption_#{hour}") do
      if apparent_power
        (method("hourly_rate_#{hour}").call.to_f / 10 * apparent_power)
      end
    end
  end

  def frequencies
    if frequency_fifty_hz and current_type == "AC"
      frequency_sixty_hz ? "50 Hz or 60 Hz" : "50 Hz"
    elsif frequency_sixty_hz and current_type == "AC"
      "60 Hz"
    else
      "n/a"
    end
  end

  def voltage_range
    if voltage_min
      voltage_max ? "#{voltage_min} V - #{voltage_max} V" : "#{voltage_min} V"
    elsif voltage_max
      "#{voltage_max} V"
    else
      "n/a"
    end
  end

  def price_max_cents
    sources.maximum(:price_eur_cents)
  end

  def price_min_cents
    sources.minimum("price_eur_cents - price_eur_cents * discount_rate / 100")
  end

  private

  def set_power_factor_and_starting_coeff
    self.power_factor = 1 if power_factor.blank?
    self.starting_coefficient = 1 if starting_coefficient.blank?
  end

end

app/controllers/appliances_controller.rb
class AppliancesController < ApplicationController
  include PowerSystemAttribution
  before_action :find_appliance, only: [:show, :edit, :update, :destroy]
  skip_after_action :verify_authorized, only: [:refresh_load]
  layout 'form', only: [:new, :create, :edit, :update, :duplicate]

  def index
    @query = params[:query]
    @page_number = params[:page]
    @use_pagination_id = params[:use].to_i
    if @query.present?
      @appliances = policy_scope(Appliance).search(@query)
      use_ids = @appliances.select(:use_id).reorder("").distinct
      @uses = policy_scope(Use).where(id: use_ids).ordered
    else
      @appliances = policy_scope(Appliance).ordered
      @uses = policy_scope(Use).ordered
    end
  end

  def show
    @sources = @appliance.sources.ordered
    @use = @appliance.use
  end

  def new
    @appliance = current_user.appliances.new
    authorize @appliance
  end

  def duplicate
    @parent_appliance = Appliance.find(params[:id])
    @appliance = @parent_appliance.dup
    @appliance.name += " -- copy"
    authorize @appliance
    @appliance.save
  end

  def create
    @appliance = current_user.appliances.new(appliance_params)
    authorize @appliance
    if @appliance.save
      flash[:notice] = "#{@appliance.name} has been created"
      redirect_to appliance_path(@appliance)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @appliance.update(appliance_params)
      update_appliance_solar_systems
      flash[:notice] = "#{@appliance.name} has been updated"
      redirect_to appliance_path(@appliance)
    else
      render :edit
    end
  end

  def destroy
    @appliance.destroy
    flash[:notice] = "#{@appliance.name} has been deleted"
    redirect_to appliances_path
  end

  def refresh_load
    @use = Use.find(params[:use_id]) if params[:use_id]
  end

  private

  def find_appliance
    @appliance = Appliance.find(params[:id])
    authorize @appliance
  end

  def update_appliance_solar_systems
    @appliance.projects.each do |project|
      @project = project
      @solar_system = @project.solar_system
      attribute_power_system_to_solar_system
    end
  end

  def appliance_params
    params.require(:appliance).permit(
      :use_id,
      :name,
      :description,
      :current_type,
      :energy_grade,
      :voltage_min,
      :voltage_max,
      :frequency_fifty_hz,
      :frequency_sixty_hz,
      :power,
      :power_factor,
      :starting_coefficient,
      :photo,
      :hourly_rate_0,
      :hourly_rate_1,
      :hourly_rate_2,
      :hourly_rate_3,
      :hourly_rate_4,
      :hourly_rate_5,
      :hourly_rate_6,
      :hourly_rate_7,
      :hourly_rate_8,
      :hourly_rate_9,
      :hourly_rate_10,
      :hourly_rate_11,
      :hourly_rate_12,
      :hourly_rate_13,
      :hourly_rate_14,
      :hourly_rate_15,
      :hourly_rate_16,
      :hourly_rate_17,
      :hourly_rate_18,
      :hourly_rate_19,
      :hourly_rate_20,
      :hourly_rate_21,
      :hourly_rate_22,
      :hourly_rate_23
    )
  end
end

app/views/appliances/_badge_current.html.erb
<% if appliance.current_type.present? %>
  <div class="badge badge-light border px-2 mr-2">
    <%= appliance.current_type %>
  </div>
<% end %>

app/views/appliances/_badge_energy.html.erb
<% if appliance.daily_consumption.present? %>
  <div class="badge badge-secondary px-2 mr-2 text-nowrap">
    <%= "#{number_with_delimiter(appliance.daily_consumption.round, delimiter: " ")} Wh/d" %>
  </div>
<% end %>

app/views/appliances/_button_destroy.html.erb
<% if policy(appliance).destroy? %>
  <%= link_to appliance_path(appliance), method: :delete, data: {confirm: 'Are you certain you want to delete this appliance?'}, class: "btn btn-outline-danger" do %>
    <i class="fas fa-trash-alt mr-1"></i>
    Delete
  <% end %>
<% end %>

app/views/appliances/_button_duplicate.html.erb
<% if policy(appliance).duplicate? %>
  <%= link_to duplicate_appliance_path(appliance), class: "my-1 ml-3 mr-sm-2 text-secondary", method: :post, remote: true, data: {confirm: "Do you want to create a clone of the applaince '#{appliance.name}'?", toggle: "tooltip"}, title:"Clone appliance" do %>
    <i class="fas fa-clone fa-fw"></i>
  <% end %>
<% end %>

app/views/appliances/_button_edit.html.erb
<% if policy(appliance).update? %>
  <%= link_to edit_appliance_path(appliance), class: "btn btn-primary mr-3" do %>
    <i class="fas fa-edit mr-1"></i>
    Edit
  <% end %>
<% end %>

app/views/appliances/_button_show.html.erb
<% if policy(appliance).show? %>
  <%= link_to appliance_path(appliance), class: "my-1 ml-3 mr-sm-2", data: {toggle: "tooltip"}, title:"Show appliance" do %>
    <i class="fas fa-eye fa-fw"></i>
  <% end %>
<% end %>

app/views/appliances/_features.html.erb
<table class="table">
  <tbody>
    <tr>
      <th scope="row" class="py-2">EU Energy grade</th>
      <td class="py-2">
        <% if appliance.energy_grade.present? %>
          <span class="badge px-2 <%= Appliance::GRADE_CLASSES[appliance.energy_grade] %>">
            <%= appliance.energy_grade %>
          </span>
        <% else %>
          n/a
        <% end %>
      </td>
    </tr>
    <tr>
      <th scope="row" class="py-2">Current type</th>
      <td class="py-2"><%= appliance.current_type.present? ? appliance.current_type : 'n/a' %></td>
    </tr>
    <tr>
      <th scope="row" class="py-2">Working frequency</th>
      <td class="py-2"><%= appliance.frequencies %></td>
    </tr>
    <tr>
      <th scope="row" class="py-2">Voltage range</th>
      <td class="py-2"><%= appliance.voltage_range %></td>
    </tr>
    <tr>
      <th scope="row" class="py-2">Active power</th>
      <td class="py-2"><%= appliance.power ? "#{number_with_delimiter(appliance.power.round, delimiter: " ")} W" : 'n/a' %></td>
    </tr>
    <tr>
      <th scope="row" class="py-2">Apparent power</th>
      <td class="py-2">
        <span class="mr-3 text-nowrap">
          <%= appliance.apparent_power ? "#{number_with_delimiter(appliance.apparent_power.round, delimiter: " ")} VA" : "n/a" %>
        </span>
        <small class="text-nowrap">
          Power factor (cos φ) : <%= appliance.power_factor ? "#{appliance.power_factor}" : "n/a" %>
        </small>
      </td>
    </tr>
    <tr>
      <th scope="row" class="py-2">Peak power</th>
      <td class="py-2">
        <span class="mr-3 text-nowrap">
          <%= appliance.peak_power ? "#{number_with_delimiter(appliance.peak_power.round, delimiter: " ")} VA" : "n/a" %>
        </span>
        <small class="text-nowrap">
          Starting coefficient : <%= appliance.starting_coefficient ? "#{appliance.starting_coefficient}" : "n/a" %>
        </small>
      </td>
    </tr>
  </tbody>
</table>

app/views/appliances/_form.html.erb
<%= simple_form_for(appliance) do |f| %>
  <%= f.error_notification %>

  <div class="border-bottom border-tertiary pb-2 mb-4" >
    <h5 class="mb-3">General information</h5>
    <%= f.association :use, as: :select, collection: policy_scope(Use) %>
    <%= f.input :name, placeholder: "Appliance designation" %>
    <%= f.input :description,
      placeholder: "Describe the appliance ...",
      input_html: { rows: "5" },
      include_blank: false
    %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="border-bottom border-tertiary pb-2 mb-4" >
    <h5 class="mb-3">Factory features</h5>
    <div class="row">
      <div class="col-12 col-sm-6">
        <h6>Current type</h6>
        <%= f.input :current_type,
          as: :radio_buttons,
          collection: Appliance::TYPES,
          wrapper: :horizontal_collection_inline,
          label: false,
          include_blank: false
        %>
      </div>
      <div class="col-12 col-sm-6 <%= 'd-none' unless appliance.current_type == 'AC' %>" id="appliance-frequency-form-group">
        <h6>Working frequency</h6>
        <div class="d-flex">
          <div>
            <%= f.input :frequency_fifty_hz,
              label: "50 Hz",
              label_html: {class: "mr-3"}
            %>
          </div>
          <div>
            <%= f.input :frequency_sixty_hz,
              label: "60 Hz",
              label_html: {class: "mr-3"}
            %>
          </div>
        </div>
      </div>
    </div>
    <h6>Voltage range (V)</h6>
    <div class="row">
      <div class="col">
        <%= f.input :voltage_min,
          wrapper: :horizontal_form,
          label: "min",
          placeholder: "200"
        %>
      </div>
      <div class="col">
        <%= f.input :voltage_max,
          wrapper: :horizontal_form,
          label: "max",
          placeholder: "230"
        %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= f.input :energy_grade,
          as: :select,
          collection: Appliance::GRADES,
          label: "EU Energy grade"
        %>
      </div>
    </div>
  </div>

  <div>
    <h5 class="mb-3">Working features</h5>
    <div class="row mb-2">
      <div class="col col-12 col-sm-4">
        <%= f.input :power,
          label: "Active power (W)",
          placeholder: "42"
        %>
      </div>
      <div class="col col-12 col-sm-4">
        <%= f.input :power_factor,
          label: "Power factor (cos φ)",
          placeholder: "0,85"
        %>
      </div>
      <div class="col col-12 col-sm-4">
        <%= f.input :starting_coefficient,
          label: "Starting coefficient",
          placeholder: "3"
        %>
      </div>
    </div>
  </div>

  <div>
    <h6>Daily load profile</h6>
    <div class="d-sm-flex justify-content-between mb-2">
      <div class="mr-sm-4">
        <p class="text-secondary small"><em>Set the default hourly use rates of the appliance, from 0 (off) to 1 (full power).</em></p>
      </div>
      <div>
        <%= link_to appliance_refresh_load_path(use_id: appliance.use_id), remote:true, class: "btn btn-secondary btn-sm w-100 text-nowrap", id: "refresh_load" do %>
          <i class="fas fa-redo-alt mr-1"></i>
          Reset default load
        <% end %>
      </div>
    </div>
    <div id="load_chart">
      <%= render 'shared/load_chart_form', f: f, collection: Appliance::RATES, day: Appliance::DAY_TIME, night: Appliance::NIGHT_TIME, electrical_load: appliance %>
    </div>
  </div>

  <div class="d-flex justify-content-end mt-3">
    <%= link_to "Cancel", :back, class: "btn btn-outline-secondary mr-2" %>
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/appliances/_index_section.html.erb
<div data-use-id="<%= use.id %>">

  <div class="d-flex pt-2 mt-4 mb-3">
    <h5><%= use.name %></h5>
    <%= render 'uses/button_edit', use: use %>
    <%= render 'uses/button_destroy', use: use %>
  </div>

  <% use_appliances = appliances.where(use_id: use.id) %>

  <% if use_appliances.present? %>
    <div class="list-group">
      <% use_appliances.each do |appliance| %>
        <%= render 'appliances/index_show', appliance: appliance %>
      <% end %>
    </div>

  <% else %>
    <div class="text-secondary small">
      No appliances recorded for this use.
      <%= link_to "Add a new one", new_appliance_path if policy(Appliance).create? %>.
    </div>
  <% end %>

</div>

app/views/appliances/_info.html.erb
<h3 class=""><%= appliance.name %></h3>
<h5 class="mb-3 text-secondary"><%= use.name %></h5>
<p><%= sanitize auto_link(markdown_to_html(appliance.description)) %></p>

app/views/appliances/_query.html.erb
<%= form_tag appliances_path, method: :get, remote: true, class: "flex-grow-1 d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Search an appliance"
  %>
  <%= button_tag class: "btn btn-primary ml-3" do %>
    <i class="fas fa-search"></i>
  <% end %>
<% end %>

<div class="mr-md-5">
  <%= link_to "Clear", appliances_path, remote: true, class: "btn btn-link btn-sm ml-md-3 mr-md-5" %>
</div>

app/views/appliances/_sources.html.erb
<h4 class="mb-4 pt-1">Price sources</h4>

<div id="source_container">
  <% if sources.present? %>
    <div class="list-group">
      <% sources.each do |source| %>
        <%= render 'sources/card', source: source %>
      <% end %>
    </div>
  <% else %>
    <%= render 'sources/no_source', appliance: appliance %>
  <% end %>
</div>

<div class="d-flex mt-3 pt-3">
  <%= render 'sources/button_new', appliance: appliance %>
</div>

app/views/appliances/index.html.erb
<%= render 'shared/back_link', path: root_path, text: "Back to home" %>

<h2 class="mb-3">My appliances</h2>

<div class="d-md-flex justify-content-between align-items-center">
  <div class="flex-grow-1 d-flex align-items-center mr-md-5 mt-4 mb-2">
    <%= render 'appliances/query' %>
  </div>
  <div class="d-flex ml-lg-5 mt-4 mb-2">
    <%= render 'appliances/button_new' %>
  </div>
</div>

<div id="results">
  <%= render 'appliances/results', uses: @uses, appliances: @appliances, page_number: @page_number, use_pagination_id: @use_pagination_id %>
</div>

<div class="d-flex mt-4 pt-3 pb-5">
  <%= render 'uses/button_new' %>
</div>

app/views/appliances/index.js.erb
function refreshInput(queryHTML) {
  const queryInput = document.getElementById('query');
  queryInput.value = (queryHTML);
}


function refreshResults(resultsHTML) {
  const queryResults = document.getElementById('results');
  queryResults.innerHTML = (resultsHTML);
}

refreshInput('<%= @query %>');
refreshResults('<%= j render "appliances/results", uses: @uses, appliances: @appliances, page_number: @page_number, use_pagination_id: @use_pagination_id %>');
document.body.dispatchEvent(new Event('ajax:complete'));