config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations"}
  root to: 'pages#home'

  namespace :admin do
    resources :users, only: [:index, :update]
  end

  resources :uses, only: [:new, :create, :edit, :update, :destroy]
  resources :appliances, only: [:index, :show, :new, :create, :edit, :update, :destroy], shallow: true do
    resources :sources, only: [:new, :create, :edit, :update, :destroy]
    member do
      post 'duplicate'
    end
  end

  resources :projects, only: [:index, :show, :new, :create, :edit, :update, :destroy], shallow: true do
    resources :project_appliances, only: [:new, :create, :edit, :update, :destroy]
    resources :solar_systems, only: [:new, :create, :edit, :update, :destroy]
    member do
      get 'appliances'
      post 'duplicate'
    end
  end

  get 'projects/public/:token', to: 'projects#public', as: 'public_project'
  post 'projects/public/:token/load', to: 'projects#load', as: 'project_load'

  get 'appliance_refresh_load', to: 'appliances#refresh_load'
  get 'project_appliance_refresh_load', to: 'project_appliances#refresh_load'

  get 'power_components', to: 'pages#power_components'
  resources :power_systems, only: [:new, :create, :edit, :update, :destroy]
  resources :batteries, only: [:new, :create, :edit, :update, :destroy]
  resources :solar_panels, only: [:new, :create, :edit, :update, :destroy]
  resources :communication_modules, only: [:new, :create, :edit, :update]
  resources :distributions, only: [:new, :create, :edit, :update]

  post 'request_registration', to: 'pages#request_registration'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :project_appliances, dependent: :destroy
  has_many :appliances, -> { distinct }, through: :project_appliances
  has_many :uses, -> { distinct }, through: :appliances
  has_one :solar_system, dependent: :destroy

  scope :ordered, -> { order(updated_at: :desc) }
  before_save :generate_unique_token
  before_save :set_prices_in_eur

  include Discounting

  include PgSearch::Model
  pg_search_scope :search,
    against: [ :name ],
    using: {
      tsearch: {
        prefix: true,
        dictionary: "english",
        any_word: true
      }
    },
    order_within_rank: "updated_at DESC"

  FREQUENCIES = ["50 Hz", "60 Hz"]
  WIRING = {
    price_min_per_appliance_eur: 50,
    price_max_per_appliance_eur: 100,
  }
  GENSET = {
    price_per_kva_eur: 850,
    o_and_m_cost_ratio: 0.1,
    efficiency: 0.28,
    lhv: 9.94,
    lifetime: 10
  }

  validates :name, presence: true
  validates :country_code, presence: true, inclusion: {in: ISO3166::Country.codes }
  validates :city, presence: true
  validates :day_time, presence: true
  validates :night_time, presence: true
  validates :voltage_min, numericality: {greater_than_or_equal_to: 0, allow_nil: true}
  validates :voltage_max, numericality: {greater_than: 0, allow_nil: true}
  validates :frequency, inclusion: {in: FREQUENCIES, allow_blank: true}
  validate :select_at_least_one_current_type

  monetize :wiring_price_min_cents, allow_nil: true, with_currency: :eur
  monetize :wiring_price_max_cents, allow_nil: true, with_currency: :eur
  monetize :price_min_cents, allow_nil: true, with_currency: :eur
  monetize :price_max_cents, allow_nil: true, with_currency: :eur
  monetize :grid_connection_charge_cents, allow_nil: true, with_model_currency: :currency
  monetize :grid_subscription_charge_cents, allow_nil: true, with_model_currency: :currency
  monetize :grid_consumption_charge_cents, allow_nil: true, with_model_currency: :currency
  monetize :grid_connection_charge_eur_cents, allow_nil: true, with_currency: :eur
  monetize :grid_subscription_charge_eur_cents, allow_nil: true, with_currency: :eur
  monetize :grid_consumption_charge_eur_cents, allow_nil: true, with_currency: :eur
  monetize :diesel_price_cents, allow_nil: true, with_model_currency: :currency
  monetize :diesel_price_eur_cents, allow_nil: true, with_currency: :eur
  monetize :genset_price_cents, allow_nil: true, with_currency: :eur
  monetize :genset_lcoe_cents, allow_nil: true, with_currency: :eur
  monetize :grid_lcoe_cents, allow_nil: true, with_currency: :eur

  def select_at_least_one_current_type
    unless current_ac? or current_dc?
      errors.add(:current_dc, "or ac must be selected")
    end
  end

  def current_array
    list = []
    list << "AC" if current_ac?
    list << "DC" if current_dc?
    list
  end

  def currents
    if current_ac? and current_dc?
      "AC / DC"
    elsif current_ac?
      "AC"
    elsif current_dc?
      "DC"
    else
      "n/a"
    end
  end

  def voltage_range
    if voltage_min
      voltage_max ? "#{voltage_min} V - #{voltage_max} V" : "#{voltage_min} V"
    elsif voltage_max
      "#{voltage_max} V"
    else
      "n/a"
    end
  end

  def country_name
    if country_code
      country = ISO3166::Country[country_code]
      country.translations[I18n.locale.to_s] || country.name
    end
  end

  def appliance_quantity
    project_appliances.sum(:quantity)
  end

  def day_time_hour
    day_time.min.zero? ? day_time.hour : day_time.hour + 1
  end

  def night_time_hour
    night_time.min.zero? ? night_time.hour : night_time.hour + 1
  end

  def apparent_power
    sum = 0
    project_appliances.each do |project_appliance|
      if project_appliance.appliance.apparent_power
        sum += project_appliance.appliance.apparent_power * project_appliance.quantity
      end
    end
    sum
  end


  def peak_power
    sum = 0
    project_appliances.each do |project_appliance|
      if project_appliance.appliance.peak_power
        sum += project_appliance.appliance.peak_power * project_appliance.quantity
      end
    end
    sum
  end

  def daily_consumption
    sum = 0
    project_appliances.each do |project_appliance|
      if project_appliance.daily_consumption
        sum += project_appliance.daily_consumption * project_appliance.quantity
      end
    end
    sum
  end

  def yearly_consumption
    (daily_consumption * 365).to_f / 1000 if daily_consumption
  end

  def daytime_consumption
    sum = 0
    project_appliances.each do |project_appliance|
      if project_appliance.daytime_consumption
        sum += project_appliance.daytime_consumption * project_appliance.quantity
      end
    end
    sum
  end

  def nighttime_consumption
    daily_consumption - daytime_consumption
  end

  (0..23).each do |hour|
    define_method("hourly_consumption_#{hour}") do
      sum = 0
      project_appliances.each do |project_appliance|
        if project_appliance.appliance.apparent_power
          sum += project_appliance.method("hourly_consumption_#{hour}").call * project_appliance.quantity
        end
      end
      sum
    end
  end

  (0..23).each do |hour|
    define_method("hourly_rate_#{hour}") do
      apparent_power.zero? ? 0 : (method("hourly_consumption_#{hour}").call.to_f / apparent_power * 10)
    end
  end

  def all_consumptions?
    result = true
    appliances.each do |appliance|
      if appliance.apparent_power.blank?
        result = false
        break
      end
    end
    result
  end

  def load_to_csv(start_date, end_date, time_format, unit, load_breakdown)
    CSV.generate(headers: true) do |csv|
      # CSV headers
      headers = ["#{time_format.capitalize}"]
      self.uses.each { |use| headers << "#{use.name} (#{unit})" } if load_breakdown == "by_use"
      headers << "Total load (#{unit})"
      csv << headers
      # 24h pattern
      pattern = []
      coeff = (unit == "VA") ? 1 : 1000
      (0..23).each do |hour|
        line = [hour]
        self.uses.each { |use| line << (use.method("hourly_consumption_#{hour}").call(self).to_f / coeff).round(5) } if load_breakdown == "by_use"
        line << (method("hourly_consumption_#{hour}").call.to_f / coeff).round(5)
        pattern << line
      end
      # CSV year extrapolation
      (start_date.mjd..end_date.mjd).each do |day|
        pattern.each do |line|
          time = start_date + (day - start_date.mjd).day + line[0].hour
          csv_line = line.dup
          csv_line[0] = (time_format == "hour") ? (time.to_i - start_date.to_i)/3600 : time.strftime("%F %R")
          csv << csv_line
        end
      end
      csv
    end
  end

  # Prices

  def wiring_price_min_cents
    if wiring? and project_appliances.present?
      WIRING[:price_min_per_appliance_eur] * appliance_quantity * 100
    end
  end

  def wiring_price_max_cents
    if wiring? and project_appliances.present?
      WIRING[:price_max_per_appliance_eur] * appliance_quantity * 100
    end
  end

  def price_min_cents
    sum = 0
    project_appliances.each do |project_appliance|
      if project_appliance.appliance.price_min_cents
        sum += project_appliance.appliance.price_min_cents * project_appliance.quantity
      end
    end
    sum += wiring_price_min_cents if wiring_price_min_cents
    sum
  end

  def price_max_cents
    sum = 0
    project_appliances.each do |project_appliance|
      if project_appliance.appliance.price_max_cents
        sum += project_appliance.appliance.price_max_cents * project_appliance.quantity
      end
    end
    sum += wiring_price_max_cents if wiring_price_max_cents
    sum
  end

  def all_prices?
    result = true
    appliances.each do |appliance|
      if appliance.price_min.blank?
        result = false
        break
      end
    end
    result
  end

  # LCOE Calculation

  def consumption_discounted
    if yearly_consumption
      energy_discounted(yearly_consumption)
    end
  end

  def genset_price_cents
    if peak_power
      (peak_power / 1000) * GENSET[:price_per_kva_eur] * 100
    end
  end

  def genset_totex_discounted_cents
    if genset_price_cents and yearly_consumption and diesel_price_cents
      capex = genset_price_cents
      totex_discounted = capex_discounted(capex, GENSET[:lifetime])
      opex_o_and_m = capex * GENSET[:o_and_m_cost_ratio]
      opex_fuel = (yearly_consumption * diesel_price_cents).to_f / (GENSET[:lhv] * GENSET[:efficiency])
      totex_discounted += opex_discounted(opex_o_and_m + opex_fuel)
      totex_discounted
    end
  end

  def genset_lcoe_cents
    unless genset_totex_discounted_cents.blank? or consumption_discounted.blank? or consumption_discounted.zero?
      genset_totex_discounted_cents / consumption_discounted
    end
  end

  def grid_connection_charge_discounted_cents
    if grid_connection_charge_eur_cents and peak_power
      initial_cost = (peak_power / 1000) * grid_connection_charge_eur_cents
      capex_discounted(initial_cost, Float::INFINITY)
    end
  end

  def grid_subscription_charge_discounted_cents
    if grid_subscription_charge_eur_cents and peak_power
      yearly_cost = (peak_power / 1000) * grid_subscription_charge_eur_cents * 12
      opex_discounted(yearly_cost)
    end
  end

  def grid_consumption_charge_discounted_cents
    if grid_consumption_charge_eur_cents and yearly_consumption
      yearly_cost = yearly_consumption * grid_consumption_charge_eur_cents
      opex_discounted(yearly_cost)
    end
  end

  def grid_lcoe_cents
    unless consumption_discounted.blank? or consumption_discounted.zero?
      charges_discounted = 0
      charges_discounted += grid_connection_charge_discounted_cents if grid_connection_charge_discounted_cents
      charges_discounted += grid_subscription_charge_discounted_cents if grid_subscription_charge_discounted_cents
      charges_discounted += grid_consumption_charge_discounted_cents if grid_consumption_charge_discounted_cents

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include PowerSystemAttribution
  before_action :find_project, only: [:show, :edit, :update, :destroy, :appliances]
  before_action :find_project_by_token, only: [:load, :public]
  skip_before_action :authenticate_user!, only: [:public]
  layout 'form', only: [:new, :create, :edit, :update, :duplicate]

  def index
    @query = params[:query]
    page_number = params[:page]
    if @query.present?
      @projects = policy_scope(Project).search(@query).page(page_number)
    else
      @projects = policy_scope(Project).ordered.page(page_number)
    end
  end

  def show
    @project_appliances = @project.project_appliances.ordered
    @uses = @project.uses.ordered
  end

  def new
    @project = current_user.projects.new
    authorize @project
  end

  def duplicate
    @parent_project = Project.find(params[:id])
    @project = @parent_project.dup
    @project.name += " -- copy"
    @project.token = SecureRandom.hex
    authorize @project
    duplicate_project_appliances
    duplicate_solar_system
    @project.save
  end

  def create
    @project = current_user.projects.new(project_params)
    authorize @project
    if @project.save
      flash[:notice] = "#{@project.name} has been created"
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      update_solar_systems
      flash[:notice] = "#{@project.name} has been updated"
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "#{@project.name} has been deleted"
    redirect_to projects_path
  end

  def appliances
    @query = params[:query]
    @page_number = params[:page]
    @use_pagination_id = params[:use].to_i
    appliance_subset = policy_scope(Appliance).where(current_type: @project.current_array)
    @appliances = @query.present? ? appliance_subset.search(@query) : appliance_subset.ordered
    use_ids = @appliances.select(:use_id).reorder("").distinct
    @uses = policy_scope(Use).where(id: use_ids).ordered
  end

  def public
    @project_appliances = @project.project_appliances.ordered
    @uses = @project.uses.ordered
    render layout: 'public'
  end

  def load
    respond_to do |format|
      filename = "#{Date.today}-rubize_foresight-#{@project.name.underscore.tr(" ","_")}.csv"
      startDate = params[:startDate].to_datetime
      endDate = params[:endDate].to_datetime
      timeFormat = params[:timeFormat]
      unit = params[:unit]
      loadBreakdown = params[:loadBreakdown]
      format.csv { send_data @project.load_to_csv(startDate, endDate, timeFormat, unit, loadBreakdown), filename: filename }
    end
  end

  private

  def find_project
    @project = Project.find(params[:id])
    authorize @project
  end

  def find_project_by_token
    @project = Project.find_by(token: params[:token])
    authorize @project
  end

  def update_solar_systems
    @solar_system = @project.solar_system
    attribute_power_system_to_solar_system
  end

  def duplicate_project_appliances
    @parent_project.project_appliances.each do |parent_project_appliance|
      @project.project_appliances.new(parent_project_appliance.dup.attributes)
    end
  end

  def duplicate_solar_system
    @project.solar_system = SolarSystem.new(@parent_project.solar_system.dup.attributes)
  end

  def project_params
    params.require(:project).permit(
      :name,
      :description,
      :country_code,
      :city,
      :day_time,
      :night_time,
      :current_ac,
      :current_dc,
      :voltage_min,
      :voltage_max,
      :frequency,
      :wiring,
      :grid_connection_charge,
      :grid_subscription_charge,
      :grid_consumption_charge,
      :diesel_price,
      :currency
    )
  end
end

app/views/projects/_appliance_button_index.html.erb
<% if policy(ProjectAppliance).new? %>
  <%= link_to appliances_project_path(project), class: "btn btn-outline-secondary flex-grow-1" do %>
    <i class="fas fa-plus mr-1"></i>
    Add an appliance to the project
  <% end %>
<% end %>

app/views/projects/_badge_power.html.erb
<% if project.apparent_power.present? %>
  <div class="badge badge-light border px-2 mr-2 text-nowrap">
    <%= "#{number_with_delimiter(project.apparent_power.round, delimiter: " ")} VA" %>
  </div>
<% end %>

app/views/projects/_badge_price.html.erb
<% if project.price_max.present? %>
  <div class="badge px-2 mr-2 badge-dark">
    <i class="fas fa-plug fa-fw mr-1"></i>
    <%= "#{project.price_min.format(no_cents: true, symbol: false, thousands_separator: " ")} -" if project.price_min != project.price_max %>
    <%= "#{project.price_max.format(no_cents: true, symbol: false, thousands_separator: " ")} #{project.price_max.currency.symbol}" %>
  </div>
<% end %>

app/views/projects/_budget.html.erb
<table class="table table-sm">
  <tbody>
    <tr class="bg-dark text-white">
      <th scope="row" class="pl-sm-2">
        Appliances
      </th>
      <td class="text-right font-weight-bold text-nowrap">
        <%= render 'shared/price_range', price_min: project.price_min, price_max: project.price_max %>
      </td>
    </tr>
    <% project.uses.each do |use| %>
      <tr>
        <th scope="row" class="font-weight-normal pl-sm-4">
          <%= use.name %>
        </th>
        <td class="text-right text-nowrap">
          <%= render 'shared/price_range', price_min: use.price_min(project), price_max: use.price_max(project) %>
        </td>
      </tr>
    <% end %>
    <% if project.wiring? %>
      <tr>
        <th scope="row" class="font-weight-normal pl-sm-4">
          Distribution wiring
        </th>
        <td class="text-right text-nowrap">
          <%= render 'shared/price_range', price_min: project.wiring_price_min, price_max: project.wiring_price_max %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% unless project.all_prices? %>
  <div class="text-warning mt-2 mb-3 small">
    <i class="fas fa-exclamation-triangle mr-1"></i>
    Price information is missing in appliance setup.
  </div>
<% end %>

app/views/projects/_button_catalog.html.erb
<% if policy(ProjectAppliance).create? %>
  <%= link_to project_project_appliances_path(project), class: "btn btn-outline-secondary flex-grow-1" do %>
    <i class="fas fa-plus mr-1"></i>
    Add an appliance to setup
  <% end %>
<% end %>

app/views/projects/_button_edit.html.erb
<% if policy(project).update? %>
  <%= link_to edit_project_path(project), class: "btn btn-primary mr-3" do %>
    <i class="fas fa-edit mr-1"></i>
    Edit
  <% end %>
<% end %>

app/views/projects/_button_show.html.erb
<% if policy(project).show? %>
  <%= link_to project_path(project), class: "my-1 ml-3 mr-sm-2", data: {toggle: "tooltip"}, title:"Show project" do %>
    <i class="fas fa-eye fa-fw"></i>
  <% end %>
<% end %>

app/views/projects/_features.html.erb
<table class="table mt-3">
  <tbody>
    <tr>
      <th scope="row" class="py-2 text-nowrap">Current type</th>
      <td class="py-2 text-nowrap"><%= project.currents %></td>
    </tr>
    <tr>
      <th scope="row" class="py-2 text-nowrap">Working frequency</th>
      <td class="py-2 text-nowrap"><%= (project.current_ac? and project.frequency.present?) ? project.frequency : "n/a" %></td>
    </tr>
    <tr>
      <th scope="row" class="py-2 text-nowrap">Voltage range</th>
      <td class="py-2 text-nowrap"><%= project.voltage_range %></td>
    </tr>
    <tr>
      <th scope="row" class="py-2 text-nowrap">Apparent power</th>
      <td class="py-2 text-nowrap"><%= project.apparent_power ? "#{number_with_delimiter(project.apparent_power.round, delimiter: " ")} VA" : "n/a" %></td>
    </tr>
    <tr>
      <th scope="row" class="py-2 text-nowrap">Peak power</th>
      <td class="py-2 text-nowrap"><%= project.peak_power ? "#{number_with_delimiter(project.peak_power.round, delimiter: " ")} VA" : "n/a" %></td>
    </tr>
  </tbody>
</table>

<% unless project.all_consumptions? %>
  <div class="text-warning mt-2 mb-3 small">
    <i class="fas fa-exclamation-triangle mr-1"></i>
    Technical features are missing in appliance setup.
  </div>
<% end %>

app/views/projects/_project_appliances.html.erb
<div id="project_appliance_container">
  <% if uses.present? %>
    <% uses.each do |use| %>
      <%= render 'projects/use_section', use: use, use_project_appliances: use.project_appliances(project), project: project, card: card %>
    <% end %>
  <% else %>
    <%= render 'project_appliances/no_project_appliance' %>
  <% end %>
</div>

app/views/projects/_query.html.erb
<%= form_tag projects_path, method: :get, remote: true, class: "flex-grow-1 d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Search a project"
  %>
  <%= button_tag class: "btn btn-primary ml-3" do %>
    <i class="fas fa-search"></i>
  <% end %>
<% end %>

<div class="mr-md-5">
  <%= link_to "Clear", projects_path, remote: true, class: "btn btn-link btn-sm ml-md-3 mr-md-5" %>
</div>

app/views/projects/_widget_genset_lcoe.html.erb
<div class="card text-lg-center">
  <div class="card-body d-flex d-lg-block align-items-center">
    <div>
      <h3 class="mb-0 mx-3">
        <i class="fas fa-gas-pump fa-fw"></i>
      </h3>
    </div>
    <div>
      <div class="small text-secondary mb-lg-2">
        Standalone diesel genset
      </div>
      <div class="lead">
        <% if project.genset_lcoe %>
          <%= "#{project.genset_lcoe.format(symbol: false, thousands_separator: " ")} #{project.genset_lcoe.currency.symbol}/kWh" %>
          <i class="fas fa-info-circle fa-fw text-secondary small"
            data-container="body"
            data-toggle="popover"
            data-placement="bottom"
            data-html="true"
            title= "Assumptions"
            data-content='<%="
              Discount rate: #{(Project::FINANCE[:discount_rate] * 100).round}%<br>
              Timeframe: #{Project::FINANCE[:years]} yr<br>
              CAPEX: #{project.genset_price.to_i} €<br>
              O&M: #{(Project::GENSET[:o_and_m_cost_ratio] * 100).round(1)}% CAPEX/yr<br>
              Fuel cost: #{project.diesel_price} €/L<br>
              Genset Lifetime: #{Project::GENSET[:lifetime]} yr<br>
              Genset Efficiency: #{(Project::GENSET[:efficiency] * 100).round}%<br>
              LHV: #{Project::GENSET[:lhv]} kWh/L
              "%>'
            >
          </i>
        <% else %>
          n/a
          <i class="fas fa-info-circle fa-fw text-secondary small"
            data-container="body"
            data-toggle="popover"
            data-placement="bottom"
            data-html="true"
            data-content="Data is missing to estimate LCOE"
            >
          </i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/appliances.html.erb
<%= render 'shared/back_link', path: project_path(@project), text: "Back to project" %>

<h3 class="mb-3">Select an appliance from catalog</h3>

<div class="d-flex align-items-center mt-4 mb-2">
  <%= render 'projects/appliance_query' %>
</div>

<div id="results" class="pb-4">
  <%= render 'projects/appliance_results', uses: @uses, appliances: @appliances, project: @project, page_number: @page_number, use_pagination_id: @use_pagination_id %>
</div>

app/views/projects/appliances.js.erb
function refreshInput(queryHTML) {
  const queryInput = document.getElementById('query');
  queryInput.value = (queryHTML);
}


function refreshResults(resultsHTML) {
  const queryResults = document.getElementById('results');
  queryResults.innerHTML = (resultsHTML);
}

refreshInput('<%= @query %>');
refreshResults('<%= j render "projects/appliance_results", uses: @uses, appliances: @appliances, project: @project, page_number: @page_number, use_pagination_id: @use_pagination_id %>');
document.body.dispatchEvent(new Event('ajax:complete'));

app/views/projects/index.html.erb
<%= render 'shared/back_link', path: root_path, text: "Back to home" %>

<h2 class="mb-3">My projects</h2>

<div class="d-md-flex justify-content-between align-items-center">
  <div class="flex-grow-1 d-flex align-items-center mr-md-5 mt-4 mb-2">
    <%= render 'projects/query' %>
  </div>
  <div class="d-flex ml-lg-5 mt-4 mb-2">
    <%= render 'projects/button_new' %>
  </div>
</div>

<div id="results" class="mt-5 mb-3">
  <%= render 'projects/results', projects: @projects, query: @query %>
</div>