config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations"}
  root to: 'pages#home'

  namespace :admin do
    resources :users, only: [:index, :update]
  end

  resources :uses, only: [:new, :create, :edit, :update, :destroy]
  resources :appliances, only: [:index, :show, :new, :create, :edit, :update, :destroy], shallow: true do
    resources :sources, only: [:new, :create, :edit, :update, :destroy]
    member do
      post 'duplicate'
    end
  end

  resources :projects, only: [:index, :show, :new, :create, :edit, :update, :destroy], shallow: true do
    resources :project_appliances, only: [:new, :create, :edit, :update, :destroy]
    resources :solar_systems, only: [:new, :create, :edit, :update, :destroy]
    member do
      get 'appliances'
      post 'duplicate'
    end
  end

  get 'projects/public/:token', to: 'projects#public', as: 'public_project'
  post 'projects/public/:token/load', to: 'projects#load', as: 'project_load'

  get 'appliance_refresh_load', to: 'appliances#refresh_load'
  get 'project_appliance_refresh_load', to: 'project_appliances#refresh_load'

  get 'power_components', to: 'pages#power_components'
  resources :power_systems, only: [:new, :create, :edit, :update, :destroy]
  resources :batteries, only: [:new, :create, :edit, :update, :destroy]
  resources :solar_panels, only: [:new, :create, :edit, :update, :destroy]
  resources :communication_modules, only: [:new, :create, :edit, :update]
  resources :distributions, only: [:new, :create, :edit, :update]

  post 'request_registration', to: 'pages#request_registration'
end

app/models/communication_module.rb
class CommunicationModule < ApplicationRecord
  belongs_to :user
  has_many :solar_systems, dependent: :destroy

  scope :persisted, -> { where.not(id: nil) }

  validates :power, numericality: {greater_than_or_equal_to: 0, allow_nil: true}, presence: true
  validates :lifetime, numericality: {greater_than: 0, allow_nil: true}, presence: true

  monetize :price_min_cents, with_model_currency: :currency
  monetize :price_min_eur_cents, with_currency: :eur, allow_nil: true
  monetize :price_max_cents, with_model_currency: :currency
  monetize :price_max_eur_cents, with_currency: :eur, allow_nil: true

  before_save :set_prices_in_eur

  def daily_consumption
    power * 24 if power
  end

  private

  def set_prices_in_eur
    if currency and Money.default_bank.get_rate(currency, :EUR)
      self.price_min_eur_cents = price_min.exchange_to(:EUR).fractional if price_min
      self.price_max_eur_cents = price_max.exchange_to(:EUR).fractional if price_max
    end
  end
end

app/controllers/communication_modules_controller.rb
class CommunicationModulesController < ApplicationController
  before_action :find_communication_module, only: [:edit, :update]
  layout 'form', only: [:new, :create, :edit, :update]

  def new
    @communication_module = current_user.communication_modules.new
    authorize @communication_module
  end

  def create
    @communication_module = current_user.communication_modules.new(communication_module_params)
    authorize @communication_module
    if @communication_module.save
      update_solar_systems
      flash[:notice] = "A new monitoring system has been created."
      redirect_to power_components_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @communication_module.update(communication_module_params)
      flash[:notice] = "The monitoring system has been updated."
      redirect_to power_components_path
    else
      render :edit
    end
  end

  private

  def update_solar_systems
    policy_scope(Project).each do |project|
      project.solar_system.update(communication_module_id: @communication_module.id)
    end
  end

  def find_communication_module
    @communication_module = CommunicationModule.find(params[:id])
    authorize @communication_module
  end

  def communication_module_params
    params.require(:communication_module).permit(
      :price_min,
      :price_max,
      :currency,
      :power,
      :lifetime
    )
  end
end

app/views/communication_modules/_badge_energy.html.erb
<% if communication_module.daily_consumption.present? %>
  <div class="badge badge-secondary px-2 mr-2 text-nowrap">
    <%= "#{number_with_delimiter(communication_module.daily_consumption.round, delimiter: " ")} Wh/d" %>
  </div>
<% end %>

app/views/communication_modules/_badge_price.html.erb
<% if communication_module.price_max_eur.present? and communication_module.price_min_eur.present? %>
  <div class="badge px-2 badge-dark">
    <%= "#{communication_module.price_min_eur.format(no_cents: true, symbol: false, thousands_separator: " ")} -" if communication_module.price_min_eur != communication_module.price_max_eur %>
    <%= "#{communication_module.price_max_eur.format(no_cents: true, symbol: false, thousands_separator: " ")} #{communication_module.price_max_eur.currency.symbol}" %>
  </div>
<% end %>

app/views/communication_modules/_button_edit.html.erb
<% if policy(communication_module).update? %>
  <%= link_to edit_communication_module_path(communication_module), class: "my-1 ml-3 mr-sm-2", data: {toggle: "tooltip"}, title:"Edit monitoring module" do %>
    <i class="fas fa-edit"></i>
  <% end %>
<% end %>

app/views/communication_modules/_button_new.html.erb
<% if policy(CommunicationModule).new? %>
  <%= link_to new_communication_module_path, class: "btn btn-outline-secondary flex-grow-1" do %>
    <i class="fas fa-plus mr-1"></i>
    New remote monitoring module
  <% end %>
<% end %>

app/views/communication_modules/_card.html.erb
<div class="list-group-item d-flex justify-content-between align-items-center" data-communication-module-id="<%= communication_module.id %>">

  <div>
    <h6>
      <i class="fas fa-wifi fa-fw mr-1"></i>
      Remote monitoring module
    </h6>
    <div class="mb-2">
      <%= render 'communication_modules/badge_energy', communication_module: communication_module %>
      <%= render 'communication_modules/badge_price', communication_module: communication_module %>
    </div>
  </div>

  <div class="d-flex flex-column flex-sm-row">
    <%= render 'communication_modules/button_edit', communication_module: communication_module %>
  </div>

</div>

app/views/communication_modules/_form.html.erb
<%= simple_form_for(communication_module) do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-sm-6">
      <%= f.input :power,
        placeholder: "42",
        label: "Power (W)"
      %>
    </div>
  </div>

  <h5 class="mb-3 mt-2">Price range (excl. tax)</h5>
  <div class="row">
    <div class="col-12 col-sm-4">
      <%= f.input :price_min,
        as: :numeric,
        placeholder: "100",
        label: "Min"
      %>
    </div>
    <div class="col-12 col-sm-4">
      <%= f.input :price_max,
        as: :numeric,
        placeholder: "150",
        label: "Max"
      %>
    </div>
    <div class="col-12 col-sm-4">
      <%= f.input :currency,
        as: :select,
        collection: Money::Currency.all
      %>
    </div>
    <div class="col-12 col-sm-6">
      <%= f.input :lifetime,
        as: :numeric,
        placeholder: "15",
        label: "Lifetime (years)"
      %>
    </div>
  </div>

  <div class="d-flex justify-content-end mt-3">
    <%= link_to "Cancel", power_components_path, class: "btn btn-outline-secondary mr-2" %>
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/communication_modules/_index.html.erb
<div id="communication_module_container">
  <% if communication_modules.present? %>
    <div class="list-group">
      <% communication_modules.each do |communication_module| %>
        <%= render 'communication_modules/card', communication_module: communication_module %>
      <% end %>
    </div>

  <% else %>
    <%= render 'communication_modules/no_communication_module' %>
  <% end %>
</div>

<div class="d-flex mt-3 pt-3">
  <%= render 'communication_modules/button_new' %>
</div>

app/views/communication_modules/_no_communication_module.html.erb
<div class="text-secondary small">
  No remote monitoring module recorded.
</div>

app/views/communication_modules/edit.html.erb
<h3 class="mb-4">Edit remote monitoring module</h3>

<%= render 'communication_modules/form',communication_module: @communication_module %>

app/views/communication_modules/new.html.erb
<h3 class="mb-4">New remote monitoring module</h3>

<%= render 'communication_modules/form',communication_module: @communication_module %>