config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations"}
  root to: 'pages#home'

  namespace :admin do
    resources :users, only: [:index, :update]
  end

  resources :uses, only: [:new, :create, :edit, :update, :destroy]
  resources :appliances, only: [:index, :show, :new, :create, :edit, :update, :destroy], shallow: true do
    resources :sources, only: [:new, :create, :edit, :update, :destroy]
    member do
      post 'duplicate'
    end
  end

  resources :projects, only: [:index, :show, :new, :create, :edit, :update, :destroy], shallow: true do
    resources :project_appliances, only: [:new, :create, :edit, :update, :destroy]
    resources :solar_systems, only: [:new, :create, :edit, :update, :destroy]
    member do
      get 'appliances'
      post 'duplicate'
    end
  end

  get 'projects/public/:token', to: 'projects#public', as: 'public_project'
  post 'projects/public/:token/load', to: 'projects#load', as: 'project_load'

  get 'appliance_refresh_load', to: 'appliances#refresh_load'
  get 'project_appliance_refresh_load', to: 'project_appliances#refresh_load'

  get 'power_components', to: 'pages#power_components'
  resources :power_systems, only: [:new, :create, :edit, :update, :destroy]
  resources :batteries, only: [:new, :create, :edit, :update, :destroy]
  resources :solar_panels, only: [:new, :create, :edit, :update, :destroy]
  resources :communication_modules, only: [:new, :create, :edit, :update]
  resources :distributions, only: [:new, :create, :edit, :update]

  post 'request_registration', to: 'pages#request_registration'
end

app/models/solar_panel.rb
class SolarPanel < ApplicationRecord
  belongs_to :user
  has_many :solar_systems, dependent: :destroy

  scope :ordered, -> { order(:technology, :power) }

  TECHNOLOGIES = [
    "Polycristalline",
    "Monocristalline"
  ]

  validates :technology, inclusion: {in: TECHNOLOGIES, allow_blank: true}, presence: true
  validates :power, numericality: {greater_than: 0, allow_nil: true}, presence: true
  validates :lifetime, numericality: {greater_than: 0, allow_nil: true}, presence: true

  monetize :price_min_cents, with_model_currency: :currency
  monetize :price_min_eur_cents, with_currency: :eur, allow_nil: true
  monetize :price_max_cents, with_model_currency: :currency
  monetize :price_max_eur_cents, with_currency: :eur, allow_nil: true

  before_save :set_prices_in_eur

  def name
    "#{technology} - #{power} Wp"
  end

  private

  def set_prices_in_eur
    if currency and Money.default_bank.get_rate(currency, :EUR)
      self.price_min_eur_cents = price_min.exchange_to(:EUR).fractional if price_min
      self.price_max_eur_cents = price_max.exchange_to(:EUR).fractional if price_max
    end
  end
end

app/controllers/solar_panels_controller.rb
class SolarPanelsController < ApplicationController
  include PowerSystemAttribution
  before_action :find_solar_panel, only: [:edit, :update, :destroy]
  layout 'form', only: [:new, :create, :edit, :update]

  def new
    @solar_panel = current_user.solar_panels.new
    authorize @solar_panel
  end

  def create
    @solar_panel = current_user.solar_panels.new(solar_panel_params)
    authorize @solar_panel
    if @solar_panel.save
      flash[:notice] = "A new solar panel has been created."
      redirect_to power_components_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @solar_panel.update(solar_panel_params)
      update_solar_systems
      flash[:notice] = "The solar panel has been updated."
      redirect_to power_components_path
    else
      render :edit
    end
  end

  def destroy
    @solar_panel.destroy
    @solar_panels = policy_scope(SolarPanel).ordered
    # flash[:notice] = "The solar panel has been deleted"
  end

  private

  def find_solar_panel
    @solar_panel = SolarPanel.find(params[:id])
    authorize @solar_panel
  end

  def update_solar_systems
    @solar_panel.solar_systems.each do |solar_system|
      @project = solar_system.project
      @solar_system = solar_system
      attribute_power_system_to_solar_system
    end
  end

  def solar_panel_params
    params.require(:solar_panel).permit(
      :technology,
      :power,
      :price_min,
      :price_max,
      :currency,
      :lifetime
    )
  end
end

app/views/solar_panels/_badge_price.html.erb
<% if solar_panel.price_max_eur.present? and solar_panel.price_min_eur.present? %>
  <div class="badge px-2 badge-dark">
    <%= "#{solar_panel.price_min_eur.format(no_cents: true, symbol: false, thousands_separator: " ")} -" if solar_panel.price_min_eur != solar_panel.price_max_eur %>
    <%= "#{solar_panel.price_max_eur.format(no_cents: true, symbol: false, thousands_separator: " ")} #{solar_panel.price_max_eur.currency.symbol}" %>
  </div>
<% end %>

app/views/solar_panels/_button_destroy.html.erb
<% if policy(solar_panel).destroy? %>
  <%= link_to solar_panel_path(solar_panel), method: :delete, remote: true, data: {confirm: 'Are you certain you want to delete this solar panel?', toggle: "tooltip"}, class: "text-danger my-1 ml-3 mr-sm-2", title:"Delete solar panel" do %>
    <i class="fas fa-trash-alt"></i>
  <% end %>
<% end %>

app/views/solar_panels/_button_edit.html.erb
<% if policy(solar_panel).update? %>
  <%= link_to edit_solar_panel_path(solar_panel), class: "my-1 ml-3 mr-sm-2", data: {toggle: "tooltip"}, title:"Edit solar panel" do %>
    <i class="fas fa-edit"></i>
  <% end %>
<% end %>

app/views/solar_panels/_button_new.html.erb
<% if policy(SolarPanel).new? %>
  <%= link_to new_solar_panel_path, class: "btn btn-outline-secondary flex-grow-1" do %>
    <i class="fas fa-plus mr-1"></i>
    New solar panel
  <% end %>
<% end %>

app/views/solar_panels/_card.html.erb
<div class="list-group-item d-flex justify-content-between align-items-center" data-solar-panel-id="<%= solar_panel.id %>">

  <div>
    <h6>
      <i class="fas fa-solar-panel fa-fw mr-1"></i>
      <span class="mr-2"><%= solar_panel.technology %></span>
      <span class="text-secondary mr-2">
        <%= "#{solar_panel.power} Wp" %>
      </span>
    </h6>
    <div class="mb-2">
      <%= render 'solar_panels/badge_price', solar_panel: solar_panel %>
    </div>
  </div>

  <div class="d-flex flex-column flex-sm-row">
    <%= render 'solar_panels/button_edit', solar_panel: solar_panel %>
    <%= render 'solar_panels/button_destroy', solar_panel: solar_panel %>
  </div>

</div>

app/views/solar_panels/_card_with_quantity.html.erb
<div class="list-group-item d-flex align-items-center pl-0 overflow-hidden">

  <div class="card-quantity position-absolute h-100 bg-secondary text-white d-flex align-items-center justify-content-center">
    <%= solar_system.solar_panel_quantity %>
  </div>

  <div class="flex-grow-1 ml-5">
    <h6>
      <i class="fas fa-solar-panel fa-fw mr-1"></i>
      <span class="mr-2"><%= solar_panel.technology %></span>
      <span class="text-secondary mr-2">
        <%= "#{solar_panel.power} Wp" %>
      </span>
    </h6>
    <div class="mb-2">
      <%= render 'solar_panels/badge_price', solar_panel: solar_panel %>
    </div>
  </div>

</div>

app/views/solar_panels/_form.html.erb
<%= simple_form_for(solar_panel) do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-sm-8">
      <%= f.input :technology,
        collection: SolarPanel::TECHNOLOGIES
      %>
    </div>
    <div class="col-sm-4">
      <%= f.input :power,
        label: 'Rated power (Wp)',
        placeholder: "270"
      %>
    </div>
  </div>

  <h5 class="mt-3">Price range (excl. tax)</h5>
  <p class="text-secondary small"><em>Include wiring and mounting equipment costs (per panel).</em></p>
  <div class="row">
    <div class="col-12 col-sm-4">
      <%= f.input :price_min,
        as: :numeric,
        placeholder: "150",
        label: "Min"
      %>
    </div>
    <div class="col-12 col-sm-4">
      <%= f.input :price_max,
        as: :numeric,
        placeholder: "200",
        label: "Max"
      %>
    </div>
    <div class="col-12 col-sm-4">
      <%= f.input :currency,
        as: :select,
        collection: Money::Currency.all
      %>
    </div>
    <div class="col-12 col-sm-6">
      <%= f.input :lifetime,
        as: :numeric,
        placeholder: "15",
        label: "Lifetime (years)"
      %>
    </div>
  </div>

  <div class="d-flex justify-content-end mt-3">
    <%= link_to "Cancel", power_components_path, class: "btn btn-outline-secondary mr-2" %>
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/solar_panels/_index.html.erb
<div id="solar_panel_container">
  <% if solar_panels.present? %>

    <% SolarPanel::TECHNOLOGIES.each do |technology| %>
      <% if solar_panels.where(technology: technology).present? %>
        <h6 class="pb-2"><%= technology %></h6>
        <div class="list-group pb-4">
          <% solar_panels.where(technology: technology).each do |solar_panel| %>
            <%= render 'solar_panels/card', solar_panel: solar_panel %>
          <% end %>
        </div>
      <% end %>
    <% end %>

  <% else %>
    <%= render 'solar_panels/no_solar_panel' %>
  <% end %>
</div>

<div class="d-flex mt-3 pt-3">
  <%= render 'solar_panels/button_new' %>
</div>

app/views/solar_panels/_no_solar_panel.html.erb
<div class="text-secondary small">
  No solar panel recorded.
</div>

app/views/solar_panels/destroy.js.erb
function hideSolarPanelCard(solarPanelId) {
  const solarPanelCard = document.querySelector(`[data-solar-panel-id='${solarPanelId}']`);
  solarPanelCard.classList.add("d-none");
  solarPanelCard.classList.remove("d-flex");
}

function showNoSolarPanelMessage(messageHTML) {
  const solarPanelContainer = document.getElementById('solar_panel_container');
  solarPanelContainer.insertAdjacentHTML('beforeend', messageHTML);
}

hideSolarPanelCard("<%= @solar_panel.id %>");
<% if @solar_panels.blank? %>
  showNoSolarPanelMessage("<%= j render 'solar_panels/no_solar_panel' %>");
<% end %>

app/views/solar_panels/edit.html.erb
<h3 class="mb-4">Edit solar panel</h3>

<%= render 'solar_panels/form', solar_panel: @solar_panel %>

app/views/solar_panels/new.html.erb
<h3 class="mb-4">New solar panel</h3>

<%= render 'solar_panels/form', solar_panel: @solar_panel %>